### ISSUE TITLE
save PCD not working

### ISSUE THREAD

**Issue by sai2602** [JokerJohn/LIO_SAM_6AXIS#48]
Hi @JokerJohn,

Firstly, Thank you so much for the work. I am currently working with LIO-SAM for a use case where my robot is indoors (where there is no GNSS data) and I want to save the estimated pose in TUM format which then goes as an input to one of my 3D object detection network. In the datasaver, I see that this is already an option to save the optimized pose to text file in TUM format. The mapOptimizationGps.cpp instantiates the dataSaver and creates the subdirectory to save the text file, but, even after my run ends (I have a bag file), the subdirectory did not have the text file. I then saw that the "saveMapService" where the actual saving happens wasn't called anywhere and so I instantiated that too. I still don't see the text file being saved. Could you please help m with this?

**Comment by JokerJohn** [comment]
After you play  your rosbag, just use the command `rosservice call /lio_sam_6axis/save_map` which will call the saveMapService.

> Hi @JokerJohn,
> 
> Firstly, Thank you so much for the work. I am currently working with LIO-SAM for a use case where my robot is indoors (where there is no GNSS data) and I want to save the estimated pose in TUM format which then goes as an input to one of my 3D object detection network. In the datasaver, I see that this is already an option to save the optimized pose to text file in TUM format. The mapOptimizationGps.cpp instantiates the dataSaver and creates the subdirectory to save the text file, but, even after my run ends (I have a bag file), the subdirectory did not have the text file. I then saw that the "saveMapService" where the actual saving happens wasn't called anywhere and so I instantiated that too. I still don't see the text file being saved. Could you please help m with this?

After you play  your rosbag, just use the command `rosservice call /lio_sam_6axis/save_map` which will call the saveMapService.

**Comment by sai2602** [comment]
Hi @JokerJohn ,

Thanks for the update. It still doesn't write the poses to the file. There is just one entry in the file and the statement "Consistent running" doesn't get printed. So, I guess the service is getting terminated after the first entry.

**Comment by sai2602** [comment]
Just an update. I have now created a standalone API that always writes the odom (extracted from dataSaver.cpp). This is working for me now, but it would be great to know why the rosservice doesn't work. Getting this up and running would be useful for me since I also would at a later stage need the other options like saving the graph, map etc.

**Comment by JokerJohn** [comment]
> Just an update. I have now created a standalone API that always writes the odom (extracted from dataSaver.cpp). This is working for me now, but it would be great to know why the rosservice doesn't work. Getting this up and running would be useful for me since I also would at a later stage need the other options like saving the graph, map etc.

Ensure that you execute the rosservice command after playing the bag package. If the save operation still fails, I speculate it might be due to the keyframe lock not successfully locking the corresponding code segment (mtx.lock()). As saving the point cloud is very time-consuming, I suggest minimizing the code segment between mtx.lock() and mtx.unlock(). You can prioritize saving the trajectory and save the point cloud map at the end. The updated code can be as follows:
`mtx.lock();
for (int i = 0; i < cloudKeyPoses6D->size(); ++i) {
    ...
}
mtx.unlock();

dataSaverPtr->saveTimes(keyframeTimes);
...
if (useGPS) dataSaverPtr->saveKMLTrajectory(lla_vec);

std::cout << "Times, isam, raw_odom, pose_odom, pose3D, pose6D: "
          << keyframeTimes.size() << " " << isamCurrentEstimate.size()
          << ", " << keyframeRawOdom.size() << " "
          << keyframePosesOdom.size() << " " << cloudKeyPoses3D->size()
          << " " << cloudKeyPoses6D->size() << std::endl;
...

pcl::PointCloud<PointType>::Ptr globalMapCloud(
        new pcl::PointCloud<PointType>());
...
// save global point cloud map
*globalMapCloud += *globalCornerCloudDS;
*globalMapCloud += *globalSurfCloudDS;
...

std::cout << "global map size: " << globalMapCloud->size() << " " << globalRawCloudDS->size() << std::endl;
dataSaverPtr->savePointCloudMap(*globalMapCloud);
...
cout << "****************************************************" << endl;
cout << "Saving map to pcd files completed: " << endl;
`
Unfortunately, I currently do not have sufficient time to update this repo. I will fix the bug as soon as I get a chance.
